import type { ChangeEvent, Dispatch, SetStateAction } from "react";

export interface SignupStepProps {
  BackButton?: () => JSX.Element;
  age?: string;
  setAge?: Dispatch<SetStateAction<string>>;
  gender?: string;
  setGender?: Dispatch<SetStateAction<string>>;
  onboardingPhotoBase64?: string | null;
  setOnboardingPhotoBase64?: Dispatch<SetStateAction<string | null>>;
  analysisLoading?: boolean;
  setAnalysisLoading?: Dispatch<SetStateAction<boolean>>;
  onboardingAnalysis?: any;
  setOnboardingAnalysis?: Dispatch<SetStateAction<any>>;
  correctedSkinType?: string;
  setCorrectedSkinType?: Dispatch<SetStateAction<string>>;
  correctedProblems?: string[];
  setCorrectedProblems?: Dispatch<SetStateAction<string[]>>;
  editingDiagnostic?: boolean;
  setEditingDiagnostic?: Dispatch<SetStateAction<boolean>>;
  showDiagnostic?: boolean;
  setShowDiagnostic?: Dispatch<SetStateAction<boolean>>;
  skinGoals?: string[];
  toggleGoal?: (goal: string) => void;
  toggleOnboardingProduct?: (product: any) => void;
  selectedOnboardingProducts?: any[];
  productSearchQuery?: string;
  setProductSearchQuery?: Dispatch<SetStateAction<string>>;
  productCatalogResults?: any[];
  onboardingScanLoading?: boolean;
  onboardingScanMessage?: string | null;
  handleOnboardingProductScan?: (e: ChangeEvent<HTMLInputElement>) => void;
  setLocationMode?: Dispatch<SetStateAction<"geo" | "manual" | null>>;
  locationMode?: "geo" | "manual" | null;
  manualCity?: string;
  setManualCity?: Dispatch<SetStateAction<string>>;
  geoLoading?: boolean;
  setGeoLoading?: Dispatch<SetStateAction<boolean>>;
  lastPeriodDate?: string;
  setLastPeriodDate?: Dispatch<SetStateAction<string>>;
  cycleDuration?: number;
  setCycleDuration?: Dispatch<SetStateAction<number>>;
  cycleStatus?: "unknown" | "none" | null;
  setCycleStatus?: Dispatch<SetStateAction<"unknown" | "none" | null>>;
  carnation?: string;
  setCarnation?: Dispatch<SetStateAction<string>>;
  skinType?: string;
  setSkinType?: Dispatch<SetStateAction<string>>;
  skinProblems?: string[];
  toggleProblem?: (problem: string) => void;
  defaultFactors?: string[];
  addDefaultFactor?: (key: string) => void;
  removeDefaultFactor?: (key: string) => void;
  selectedPlan?: "monthly" | "yearly";
  setSelectedPlan?: Dispatch<SetStateAction<"monthly" | "yearly">>;
  PLANS?: Record<"monthly" | "yearly", { id: string; price: string; period: string; subtext: string; badge?: string }>;
  setStep?: Dispatch<SetStateAction<number>>;
  loading?: boolean;
  setLoading?: Dispatch<SetStateAction<boolean>>;
  password?: string;
  setPassword?: Dispatch<SetStateAction<string>>;
  email?: string;
  setEmail?: Dispatch<SetStateAction<string>>;
  firstName?: string;
  setFirstName?: Dispatch<SetStateAction<string>>;
  lastName?: string;
  setLastName?: Dispatch<SetStateAction<string>>;
  step?: number;
  personalizedRecommendationsConsent?: boolean;
  setPersonalizedRecommendationsConsent?: Dispatch<SetStateAction<boolean>>;
  aiLearningConsent?: boolean;
  setAiLearningConsent?: Dispatch<SetStateAction<boolean>>;
  productResearchConsent?: boolean;
  setProductResearchConsent?: Dispatch<SetStateAction<boolean>>;
  marketingShareConsent?: boolean;
  setMarketingShareConsent?: Dispatch<SetStateAction<boolean>>;
}
